### PR TITLE
fix merging of distribution files with repositories without a release entry

### PR DESCRIPTION
**Pull request by dirk-thomas**
Addresses #49.

### CODE REVIEW

**Comment by tfoote** [comment]
lgtm

**Comment by mikeferguson** [comment]
This works for me! Thanks for the very quick fix @dirk-thomas

**Comment by dirk-thomas** [comment]
@esteve @wjwwood Please review.

**Comment by wjwwood** [comment]
+1

**Comment by esteve** [comment]
+1

**Pull request merged**
