### PR TITLE
[Windows] More portable way to check Git executable

### PR DESCRIPTION
**Pull request by seanyen**
On Windows, by its convention, the executable has a file extension `.exe` and this pull request is to add that for searching Git executable.

### CODE REVIEW

**Comment by cottsay** [comment]
Will this handle `git.cmd` too?

**Comment by mikepurvis** [comment]
I would handle this kind of thing in the `_find_executable` helper itself, though I suppose in this case it's private to the module so it doesn't much matter:

https://github.com/ros-infrastructure/rosdistro/blob/15198de618b6fcd1dd6160fc676b9c544d102a15/src/rosdistro/vcs.py#L83-L88

**Comment by dirk-thomas** [comment]
> I would handle this kind of thing in the `_find_executable` helper itself

I don't think appending `.exe` is in 100% of the cases the correct assumption.

**Comment by seanyen** [comment]
> Will this handle `git.cmd` too?

Where was this `git.cmd`? Is it a wrapper for Git? I am using `git version 2.27.0.windows.1` and I didn't see this file.

**Comment by cottsay** [comment]
> Where was this `git.cmd`?

I'm not aware of any setups which install `git.cmd` by default, but while I was at Microsoft, we used `*.cmd` wrappers all the time to avoid adding excess directories to our `PATH`.

Certainly not a blocker, but I was curious. I would think that a complete implementation of `_find_executable` would be able to find `*.cmd` files as well as `*.exe`, since that's the behavior exhibited by `where` and CMD itself.

**Comment by seanyen** [comment]
> Certainly not a blocker, but I was curious. I would think that a complete implementation of `_find_executable` would be able to find `*.cmd` files as well as `*.exe`, since that's the behavior exhibited by `where` and CMD itself.

Ah I see. In such case, I think we can peak `%PATHEXT%` to append the possible file extensions which `CMD.exe` recognize. [Link](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/start#remarks).

**Comment by dirk-thomas** [comment]
> I think we can peak `%PATHEXT%` to append the possible file extensions which `CMD.exe` recognize.

That sounds good to me. We already do the same in e.g. `ros2 run`. Can you please update the PR accordingly?

**Comment by dirk-thomas** [comment]
Thanks for the patch.

**Pull request merged**
