### PR TITLE
github.py:  encode('utf-8') package XML before parsing

### PR DESCRIPTION
**Pull request by zultron**
The `_get_url_contents()` function decodes downloaded content before
returning it.

The `github_source_manifest_provider()` function calls
`package.parse_package_string()` on this content, which passes it to
`xml.dom.minidom.parseString()`.  That expects input to be encoded.

This patch encodes that content before sending it out to
`package.parse_package_string()`.

### CODE REVIEW

**Comment by zultron** [comment]
Earlier I erroneously filed a PR at ros-infrastructure/catkin_pkg#252.  Clearly I don't understand my python Unicode, so please check this carefully.

**Comment by dirk-thomas** [comment]
There are numerous manifest files with special characters in already released packages for which the process seem to work just fine. Please provide more information how to reproduce the problem.

**Comment by zultron** [comment]
@dirk-thomas Thanks for looking at this.  I can't explain why this bug isn't triggered in released packages, but I have reproduced the bug in the tests, narrowed it down to Python 2 only, and with some incremental pushing the results are visible in the Travis tests in this PR.

The second-to-top commit adjusts the tests to better mimic the behavior of `rosdistro.manifest_provider.github._get_url_contents()` by decoding the XML bytes into a Unicode string before returning it.  The bug is then visible in the Python 2 tests, shown [failing in this test run][tci-fail].

The top commit is the fix in the original PR, shown [passing in this run][tci-pass].

I put as much explanation as I'm able into the commit log, but I'm not able to explain what changed in Python 3 (or how this bug escaped attention in the past).

[tci-fail]: https://travis-ci.org/ros-infrastructure/rosdistro/builds/509268781
[tci-pass]: https://travis-ci.org/ros-infrastructure/rosdistro/builds/509272184

**Comment by dirk-thomas** [comment]
I don't think patching the parameter of `parse_package_string()` is the right approach. Please see ros-infrastructure/catkin_pkg#253 for an alternative fix making the function more flexible.

**Comment by zultron** [comment]
I'm fine with however you want to fix this.  The first commit that fixes the unit tests still ought to stay, IMO, even if you ultimately go with the fix in ros-infrastructure/catkin_pkg#253.  Let me know and I can pop the top commit off this PR.

**Comment by zultron** [comment]
...upon second look at the other PR, I think the unit test change here can go, too, since it's incomplete and doesn't test both cases.  I'm closing this one out.

**Pull request closed without merging**
