### PR TITLE
split Debian package into scripts and modules

### PR DESCRIPTION
**Pull request by dirk-thomas**
Same as for [catkin-pkg](ros-infrastructure/catkin_pkg#157).

After this has been reviewed and merged I will release version 0.6.0.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
https://github.com/ros-infrastructure/rosdistro/pull/95/files#diff-419aa3e2c65a318d41b25af356c30f36R13 and following.

**Comment by dirk-thomas** [comment]
The failing test is due to the GitHub API throttling the requests from Travis.

**Comment by dirk-thomas** [comment]
For this to actually work `rospkg` needs to be split, too... :worried:

**Comment by mikepurvis** [comment]
What is the objective here?

**Comment by dirk-thomas** [comment]
Side by side installation of Python 2 and 3 modules, see the referenced catkin-pkg ticket for more information.

**Pull request merged**
